### ISSUE TITLE
Feature-1: Create the layout of the website

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#1]
## 💰 Motivation

This shouldn't be here because it is just creating the page.

## 📐 Plan

Making the home page, user page, other user's pages, and how the post should look like.

## 🖼️ Wireframes

Will be back

## ✅ Task List
- [x] Create the Nav Bar
  - [x] With the ability to route to your user page and also back to the home page.
- [ ] Create the layout for the homepage.
  - [ ] Have it show the user name of the poster
  - [ ] have it show the post
  - [ ]  have it have a dislike, like, and dislike button
  - [ ] have it display the time of the post creation
  - [ ] if post is yours also have an edit button.
- [ ] Create the user's page:
  - [ ] Have it show the user's profile picture and their username with the amount of posts, followers, and following they have
  - [ ] Have it show the post made by the user.
  - [ ] Have a button that show that lets you edit your account
- [ ] Create the other user's page:
  - [ ] Should look exactly like the user's page but instead of having the edit button they have a follow button.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
