### ISSUE TITLE
Feature-2 Create the ability to create a post

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#2]
## 💰 Motivation

If the user would like to make a post to the website for all others to see

## 📐 Plan

Allow users to create a post.

## 🖼️ Wireframes

Will be back to fix this.

## ✅ Task List
- [ ] Add a button that to open the create the post page:
   - [ ] Add a route to open up the create post page.
- [ ] The Create post page should contain:
  - [ ] A input box to accept photo URL links to upload an image (not required to post)
  - [ ] The image entered into the photo URL input should appear underneath the input box
  - [ ] A input box to accept the text for the post (Text is required to post)
- [ ] When user selects cancel button
  - [ ] when user selects cancel button it will reset form and route back to homepage
- [ ] When user selects the post button:
  - [ ] Will send the text to the database and the photo URL if it is entered into.
  - [ ] Will add the post to the user's page and post it onto the the home page of the website
  - [ ] Will reroute back to the homepage.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
