### ISSUE TITLE
Feature 4: Deleting a user's post.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#4]
## 💰 Motivation

If a user decides that they no longer want to have a post, they should be able to delete it.

## 📐 Plan

Allow users to delete an post from the page.

## 🖼️ Wireframes

Will be back

## ✅ Task List
- [ ] Add a button to the edit page with delete on it
- [ ] Show a confirmation modal when the user clicks **Delete Post**
- [ ] When the user clicks **Cancel**, hide the modal.
- [ ] When the user clicks **Confirm**:
  - [ ] remove the corresponding post from the database.
  - [ ] hide the modal.
  - [ ] swap to back to the user's page.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
