### ISSUE TITLE
Feature 5: User can like and dislike a post.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#5]
## 💰 Motivation

What social media website doesn't have a like button and also I think dislike buttons are important also

## 📐 Plan

Allow users to like or dislike a post.

## 🖼️ Wireframes

Will be back

## ✅ Task List
- [ ] When the user clicks on the like heart/button
  - [ ] Will change the heart to red
  - [ ] it will also increase the number of likes next to the heart up by one.
  - [ ] Should be done through the database
- [ ] When the user clicks on the dislike heart/button
  - [ ] Will change the heart to blue
  - [ ] it will also increase the number of dislikes next to the broken heart up by one.
  - [ ] Should be done through the database
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
