### ISSUE TITLE
Feature 6: User's can Comment on the a post

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#6]
## 💰 Motivation

If a user wants to say their thoughts about the post they should be able to.

## 📐 Plan

Allow users leave a comment on a post.

## 🖼️ Wireframes

Will be back

## ✅ Task List
- [ ] Add a button next to the like and dislike button for the comments
 - [ ] When selected it will open the comments and display them.
 - [ ] Above all comments there will be a create comment button.
 - [ ] When selected it will open a modal
     - [ ] inside the modal it will have a text box to have the comment made
     - [ ] if user selects comment button the comment will be made.
     - [ ] if user selects cancel it will close the modal.
 - [ ] After posted it will appear on the comments list.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
