### ISSUE TITLE
Feature 8: User can be followed and follow other users and view following/followers list.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#7]
## 💰 Motivation

What social media doesn't have a following system. I mean we all want to add our friends so we should be able to 

## 📐 Plan

Allow users to follow others and can be followed back

## 🖼️ Wireframes

Will be back

## ✅ Task List
- [ ] If User goes onto another's page and clicks on the following button.
  - [ ] It will make the other users followers count go up one
  - [ ] the users following counter on their page will go up by one
- [ ] When user clicks on their own or other users following/followers count
  - [ ] A list will appear with all the people who are following them or who the user is following.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
