### ISSUE TITLE
Feature 7: User can view the post other user's pages when clicking on their User name.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/full-stack-project#8]
## 💰 Motivation

If a user decides they want to look at others page they should be able to.

## 📐 Plan

Allow users to view other user's page.

## 🖼️ Wireframes

Will be back

## ✅ Task List
- [ ] When a user selects another users User name
  - [ ] It will route the user to the page of the User they clicked on.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
